import { NextPage } from "next";
import Head from "next/head";
import LandingPage from "@/components/LandingPage";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>nodewave</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <Navigation />
      <LandingPage />
      <Footer />
    </>
  );
};

export default Index;
